FROM node:16.17.0-alpine AS base
RUN npm i -g pnpm

FROM base AS dependencies

WORKDIR /turbo-monorepo
COPY ./package.json pnpm-lock.yaml ./
RUN pnpm install

FROM base AS build

WORKDIR /turbo-monorepo
COPY . .
COPY --from=dependencies /turbo-monorepo/node_modules ./node_modules
RUN pnpm build

