version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7

jobs:
  dev-lint:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install:
          node-version: '16.17.0'
      - run: npm install -g pnpm
      - run : pnpm install
      - run : pnpm web:lint

workflows:
  web-dev:
    jobs:
      - dev-lint

