version: 2.1

jobs:
  build:
    working_directory: ~/circleci-monorepo
    docker:
      - image: "circleci/node:16.17.0"
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: pnpm install

