version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  sample:
    working_directory: ~/circleci-monorepo
    docker:
      - image: circleci/node:16.17.0
    steps:
      - checkout
    name: Install Dependencies
    command: pnpm install

