version: 2.1

jobs:
  sample:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command: pnpm install

workflows:
  orb-free-workflow:
    jobs:
      - sample

