name: code-analysis
on:
  push:
    branches:
      - develop
  pull_request:
#    paths:
#      - 'apps/docs/**'
#      - 'apps/web/**'
    types: [opened, synchronize, reopened]
jobs:
#  test-print-github:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Print Inputs
#        run: |
#          echo "event path: ${{ steps.watch.outputs.changed }}"
#          echo "web : ${{ steps.watch.outputs.changed.web }}"


  watch-file-changed:
    name: watch file changed
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16.x]
    outputs:
      web: ${{ steps.filter.outputs.web }}
    steps:
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node}}
      - name: Filter Paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            web:
              - 'apps/web/**'

      - name: Print Inputs
        run: |
          echo "event: ${{ steps.changes.outputs.web }}"

  sonar-cloud-ci-web:
    needs: watch-file-changed
    steps:
      - run : echo ${{ needs.watch-file-changed.outputs.web }}
#    if: ${{ needs.watch-file-changed.outputs.web == 'true' }}
#    needs: watch-file-changed
#    uses: ./.github/workflows/sonar_cloud_scan.yml
#    with:
#      projectName: 'SonarCloud Web Scan'
#      projectBaseDir: /apps/web
#    secrets:
#      token: ${{ secrets.SONAR_TOKEN_WEB }}
#    steps:
#      run: |
#        echo "event: ${{ steps.changes.outputs.web }}"
#
#  sonar-cloud-ci-docs:
#    uses: ./.github/workflows/sonar_cloud_scan.yml
#    with:
#      projectName: 'SonarCloud Docs Scan'
#      projectBaseDir: /apps/docs
#    secrets:
#      token: ${{ secrets.SONAR_TOKEN_DOCS }}