name: code-analysis
on:
  push:
    branches:
      - develop
  pull_request:
#    paths:
#      - 'apps/docs/**'
#      - 'apps/web/**'
    types: [opened, synchronize, reopened]
jobs:
  changes:
    name: watch file changed
    runs-on: ubuntu-latest
    permissions:
          pull-requests: read
    strategy:
      matrix:
        version: [16.x]
    outputs:
      web: ${{ steps.filter.outputs.web }}
    steps:
      - name: Filter Paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            web:
              - 'apps/web/**'

      - name: Print Inputs
        run: |
          echo "event: ${{ steps.changes.outputs.web }}"

  sonar-cloud-ci-web:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - run: |
          echo "output: ${{ needs.changes.outputs.web }}"
          echo "path: ${{ steps.changes.outputs.web }}"

#    if: ${{ needs.changes.outputs.web == 'true' }}
#    uses: ./.github/workflows/sonar_cloud_scan.yml
#    with:
#      projectName: 'SonarCloud Web Scan'
#      projectBaseDir: /apps/web
#    secrets:
#      token: ${{ secrets.SONAR_TOKEN_WEB }}
#
#  sonar-cloud-ci-docs:
#    uses: ./.github/workflows/sonar_cloud_scan.yml
#    with:
#      projectName: 'SonarCloud Docs Scan'
#      projectBaseDir: /apps/docs
#    secrets:
#      token: ${{ secrets.SONAR_TOKEN_DOCS }}