name: code-analysis
on:
  push:
    branches:
      - develop
  pull_request:
#    paths:
#      - 'apps/docs/**'
#      - 'apps/web/**'
    types: [opened, synchronize, reopened]
jobs:
 # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      web: ${{ steps.filter.outputs.web }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          web:
            - 'apps/web/**'
          docs:
            - 'frontend/**'

  # JOB to build and test backend code
  backend:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "output: ${{ needs.changes.outputs.web }}"

  sonar-cloud-ci-web:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    uses: ./.github/workflows/sonar_cloud_scan.yml
    with:
      projectName: 'SonarCloud Web Scan'
      projectBaseDir: /apps/web
    secrets:
      token: ${{ secrets.SONAR_TOKEN_WEB }}

  sonar-cloud-ci-docs:
    needs: changes
    uses: ./.github/workflows/sonar_cloud_scan.yml
    with:
      projectName: 'SonarCloud Docs Scan'
      projectBaseDir: /apps/docs
    secrets:
      token: ${{ secrets.SONAR_TOKEN_DOCS }}

#  changes:
#    name: watch file changed
#    runs-on: ubuntu-latest
#    permissions:
#          pull-requests: read
#    strategy:
#      matrix:
#        version: [16.x]
#    outputs:
#      web: ${{ steps.filter.outputs.web }}
#    steps:
#      - name: Filter Paths
#        uses: dorny/paths-filter@v2
#        id: changes
#        with:
#          filters: |
#            web:
#              - 'apps/web/**'
#
#      - name: Print Inputs
#        run: |
#          echo "event: ${{ steps.changes.outputs.web }}"
#
#  sonar-cloud-ci-web:
#    runs-on: ubuntu-latest
#    needs: changes
#    steps:
#      - run: |
#          echo "output: ${{ needs.changes.outputs.web }}"
#          echo "path: ${{ steps.changes.outputs.web }}"
#
##    if: ${{ needs.changes.outputs.web == 'true' }}
##    uses: ./.github/workflows/sonar_cloud_scan.yml
##    with:
##      projectName: 'SonarCloud Web Scan'
##      projectBaseDir: /apps/web
##    secrets:
##      token: ${{ secrets.SONAR_TOKEN_WEB }}
##
##  sonar-cloud-ci-docs:
##    uses: ./.github/workflows/sonar_cloud_scan.yml
##    with:
##      projectName: 'SonarCloud Docs Scan'
##      projectBaseDir: /apps/docs
##    secrets:
##      token: ${{ secrets.SONAR_TOKEN_DOCS }}