name: sonar-cloud-ci
on:
  workflow_call:
    inputs:
      projectName:
        description: 'SonarCloud Scan'
        default: 'SonarCloud Scan'
        required: true
        type: string
      projectBaseDir:
        description: 'Base directory of the project'
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  SonarCloudScan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read

    # Set job outputs to values from filter step
    outputs:
      web: ${{ steps.filter.outputs.web }}
      docs: ${{ steps.filter.outputs.docs }}

    strategy:
      matrix:
        version: [16.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node}}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
            docs:
              - 'frontend/**'

      - name: print path name
        run: |
          echo "web: ${{ steps.filter.outputs.web }}"
          echo "docs: ${{ steps.filter.outputs.docs }}"

      - name: ${{ inputs.projectName }}
        if: steps.filter.outputs.web == 'true' || steps.filter.outputs.docs == 'true'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.token }}
        with:
          projectBaseDir: ${{github.workspace}}${{ inputs.projectBaseDir }}