name: merge_branch_code_anaylsis
on:
  push:
    branches:
      - develop
jobs:
  sonar-cloud-ci-web:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    uses: ./.github/workflows/sonar_cloud_scan.yml
    with:
      projectName: 'SonarCloud Web Scan'
      projectBaseDir: /apps/web
    secrets:
      token: ${{ secrets.SONAR_TOKEN_WEB }}

  sonar-cloud-ci-docs:
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    uses: ./.github/workflows/sonar_cloud_scan.yml
    with:
      projectName: 'SonarCloud Docs Scan'
      projectBaseDir: /apps/docs
    secrets:
      token: ${{ secrets.SONAR_TOKEN_DOCS }}