name: merge_branch_code_anaylsis
on:
  push:
    branches:
      - develop
jobs:
   # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    strategy:
      matrix:
        version: [16.x]

    # Set job outputs to values from filter step
    outputs:
      web: ${{ steps.filter.outputs.web }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        # This may save additional git fetch roundtrip if
        # merge-base is found within latest 20 commits
        fetch-depth: 20

    - name: Setup node version
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node}}

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: develop
        filters: |
          web:
            - 'apps/web/**'
          docs:
            - 'frontend/**'

  # JOB to build and test backend code
  backend:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "output: ${{ needs.changes.outputs.web }}"

  sonar-cloud-ci-web:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    uses: ./.github/workflows/sonar_cloud_scan.yml
    with:
      projectName: 'SonarCloud Web Scan'
      projectBaseDir: /apps/web
    secrets:
      token: ${{ secrets.SONAR_TOKEN_WEB }}

  sonar-cloud-ci-docs:
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    uses: ./.github/workflows/sonar_cloud_scan.yml
    with:
      projectName: 'SonarCloud Docs Scan'
      projectBaseDir: /apps/docs
    secrets:
      token: ${{ secrets.SONAR_TOKEN_DOCS }}